# Prefix binding
unbind C-b
set-option -g prefix C-q
bind-key C-q send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf

# General Bindings

# Navigate panes with Vim-like keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with Vim-like keys (capitalized)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Enter copy mode with Prefix + Enter
bind Enter copy-mode

# Settings
set -g mouse on
set -g base-index 1
set-option -g allow-rename off

