
[window]
dimensions = { columns = 108, lines = 48 }
title = "Alacritty"

[font]
normal.family = "monospace"
bold.family = "monospace"
italic.family = "monospace"
bold_italic.family = "monospace"

size = 10
