
[window]
dimensions = { columns = 130, lines = 28 }
title = "Alacritty"

[font]
normal.family = "monospace"
bold.family = "monospace"
italic.family = "monospace"
bold_italic.family = "monospace"

size = 11

[colors.primary]
background = '#000000'
foreground = '#ffbb88'

[colors.normal]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#aaaa00'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'
