
[window]
dimensions = { columns = 130, lines = 28 }
title = "Alacritty"

# [font]
# normal.family = "BigBlueTermPlus Nerd Font Mono"
# bold.family = "BigBlueTermPlus Nerd Font Mono"
# italic.family = "BigBlueTermPlus Nerd Font Mono"
# bold_italic.family = "BigBlueTermPlus Nerd Font Mono"

# size = 11

[colors.primary]
background = '#000000'
foreground = '#ffbb88'

[colors.normal]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#aaaa00'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'
