
[window]
dimensions = { columns = 120, lines = 30 }
title = "Bourne Again Shell"

[font]
normal.family = "BigBlueTermPlus Nerd Font Mono"
bold.family = "BigBlueTermPlus Nerd Font Mono"
italic.family = "BigBlueTermPlus Nerd Font Mono"
bold_italic.family = "BigBlueTermPlus Nerd Font Mono"

size = 11

[colors.primary]
background = '#000000'
foreground = '#aaaaaa'

[colors.normal]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#aaaa00'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'
