;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dired-flag-file-deletion
	dired-next-line
	dired-previous-line
	evil-backward-char
	evil-force-normal-state
	evil-forward-char
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-substitute
	evil-undo
	))

(setq mc/cmds-to-run-once
      '(
	evil-change
	evil-delete
	evil-exit-visual-state
	evil-search-next
	evil-yank
	keyboard-escape-quit
	))
